name: "Cellar Door"
description: "This is just the beginning..."
author: "oumu"

# url: "http://localhost:4000"
url: "http://oumu.github.io/Heather"

exclude: [README.md, Rakefile]
paginate: 16
permalink: /:title
